### 1. Создать Person
POST http://localhost:8080/person
Content-Type: application/json

{
  "firstname": "Ivan",
  "surname": "Ivanov",
  "lastname": "Ivanovich",
  "birthday": "2000-01-15"
}

### 2. Добавить Message пользователю (person id=1)
POST http://localhost:8080/person/1/message
Content-Type: application/json

{
  "title": "Hello",
  "text": "World",
  "time": "2026-06-23T20:00:00"
}

### 3. Список сообщений пользователя
GET http://localhost:8080/person/1/message

### 4. Сообщение пользователя по id
GET http://localhost:8080/person/1/message/1

### 5. BAD_REQUEST — пользователь не существует
POST http://localhost:8080/person/999/message
Content-Type: application/json

{
  "title": "Test",
  "text": "Test",
  "time": "2026-06-23T20:00:00"
}

### 6. Удалить сообщение у пользователя
DELETE http://localhost:8080/person/1/message/1

### 7. PUT Person
PUT http://localhost:8080/person/1
Content-Type: application/json

{
  "firstname": "Petr",
  "surname": "Petrov",
  "lastname": "Petrovich",
  "birthday": "1999-05-20"
}

### 8. Все Person
GET http://localhost:8080/person

### 9. Все Message
GET http://localhost:8080/message
